In [3]:
import torch


## load new_model

In [18]:
model_path = 'output/FedMA_skf2c_source-only/FedMA_VOC2007_foggytrain1_12.pth'
new_frcnn_model = torch.load(model_path)
new_frcnn_model

OrderedDict([('backbone.vgg_block1.0.conv1.weight',
              tensor([[[[ 4.2947e-01,  3.7347e-01, -6.1360e-02],
                        [ 2.7477e-01,  3.8681e-02, -3.6722e-01],
                        [-5.7468e-02, -2.6225e-01, -3.5010e-01]],
              
                       [[ 5.5038e-01,  4.4007e-01, -8.1387e-02],
                        [ 3.4574e-01,  4.0632e-02, -4.5350e-01],
                        [-5.8635e-02, -3.3067e-01, -4.8503e-01]],
              
                       [[ 4.8002e-01,  4.0855e-01, -6.5146e-02],
                        [ 3.1048e-01,  5.0202e-02, -4.0338e-01],
                        [-5.0872e-02, -2.8523e-01, -4.1852e-01]]],
              
              
                      [[[ 1.1727e-01,  1.6206e-01,  1.3569e-01],
                        [ 1.4835e-01,  2.0230e-01,  1.6169e-01],
                        [ 1.2934e-01,  1.7157e-01,  1.3871e-01]],
              
                       [[ 2.0877e-02,  4.7341e-02,  4.1854e-02],
                       

## load old model

In [5]:
def load_model(imdb_classes,model_path, args,cfg):
    model = initial_network(imdb_classes,args)
    checkpoint = torch.load(model_path)
    
    if args.mGPUs:
        model.module.load_state_dict(checkpoint['model'])
    else:
        model.load_state_dict(checkpoint['model'])
    
    optimizer = getOptimizer(model,args,cfg)
    optimizer.load_state_dict(checkpoint['optimizer'])
    
    start_round = checkpoint['round']
    
    return model,optimizer, start_round

In [7]:
imdb_classes =  ('__background__',  # always index 0
                          'person',
                          'people','cyclist'
                         )

class Arguments():
    def __init__(self):
        self.class_agnostic =False
        self.epochs = 3
        self.lr = 0.001
        self.lr_decay_step = 4
        self.dataset = 'KAIST'
        self.net = 'vgg16'
        self.batch_size = 24
        self.nw = 2
        self.cuda = True
        #self.round = 10
        self.mGPUs=True
        self.optimizer ="sgd"
        self.k=5
        #self.device = th.device("cpu")
        
args = Arguments()

In [10]:
from model.utils.config import cfg # ../FedWCD
test_model_path = "models/vgg16/KAIST/wkAVG_cr/faster_rcnn_KAIST_AVG_1.pth"
my_model,optimizer, start_round = load_model(imdb_classes,test_model_path, args,cfg)

ModuleNotFoundError: No module named 'model'

DataParallel(
  (module): vgg16(
    (RCNN_rpn): _RPN(
      (RPN_Conv): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (RPN_cls_score): Conv2d(512, 24, kernel_size=(1, 1), stride=(1, 1))
      (RPN_bbox_pred): Conv2d(512, 48, kernel_size=(1, 1), stride=(1, 1))
      (RPN_proposal): _ProposalLayer()
      (RPN_anchor_target): _AnchorTargetLayer()
    )
    (RCNN_proposal_target): _ProposalTargetLayer()
    (RCNN_roi_pool): ROIPool(output_size=(7, 7), spatial_scale=0.0625)
    (RCNN_roi_align): ROIAlign(output_size=(7, 7), spatial_scale=0.0625, sampling_ratio=0)
    (RCNN_base): Sequential(
      (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): ReLU(inplace)
      (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (3): ReLU(inplace)
      (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
      (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (6): ReLU(inplace)
      (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (8): ReLU(inplace)
      (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
      (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (11): ReLU(inplace)
      (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (13): ReLU(inplace)
      (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (15): ReLU(inplace)
      (16): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
      (17): Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (18): ReLU(inplace)
      (19): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (20): ReLU(inplace)
      (21): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (22): ReLU(inplace)
      (23): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
      (24): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (25): ReLU(inplace)
      (26): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (27): ReLU(inplace)
      (28): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (29): ReLU(inplace)
    )
    (RCNN_top): Sequential(
      (0): Linear(in_features=25088, out_features=4096, bias=True)
      (1): ReLU(inplace)
      (2): Dropout(p=0.5)
      (3): Linear(in_features=4096, out_features=4096, bias=True)
      (4): ReLU(inplace)
      (5): Dropout(p=0.5)
    )
    (RCNN_cls_score): Linear(in_features=4096, out_features=4, bias=True)
    (RCNN_bbox_pred): Linear(in_features=4096, out_features=16, bias=True)
  )
)

## WCD value

In [23]:
def rcnn_intermediate(model, x):
    """ Get intermediate results of specifc model.
        Note: This is NOT a generalized function for all torch models,
              due to the different arch. of models.
    """
    from torch.nn import MaxPool2d, AdaptiveAvgPool2d
    
    # forward the features layers of VGG.
    for l in list(model)[0]:
        x = l(x)
        
    x = MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)(x)   
    
    x = AdaptiveAvgPool2d(output_size=(7, 7))(x)
    
    # flatten for FC layers.
    x = x.view(x.shape[0], -1)

#     # go through FC layers.
#     for l in list(model.RCNN_top.modules())[0]:
#         x = l(x)

    return x


In [24]:
def get_features(frcnn_model, imgs, batch_sz=64):
    """ Get intermediate result from FRCNN model.
    Args : frcnn_model - torch model.
           imgs - img list with proper format.
    """
    
    outputs = []
    n_batch = len(imgs)//batch_sz
    res_batch = len(imgs)%batch_sz    

    with torch.no_grad():
        for i in range(n_batch):
            in_batch = torch.cat(imgs[i*batch_sz:(i+1)*batch_sz]).to('cuda')
            x = rcnn_intermediate(frcnn_model, in_batch)
            in_batch.to('cpu')
            outputs.append(x)

        # last incomplete batch.
        in_batch = torch.cat(imgs[-res_batch:]).to('cuda')
        x = rcnn_intermediate(frcnn_model, in_batch)
        in_batch.to('cpu')
        outputs.append(x)

    outputs = torch.cat(outputs)
    X = outputs.to('cpu').numpy()
    
    return X


### load image (old)

In [11]:
import pickle
testimg_pickle_path = '../FedWCD/data/pickle/MI3_test_3325.pkl'
with open(testimg_pickle_path, 'rb') as handle:
    test_images = pickle.load(handle)

In [16]:
test_images

[tensor([[[[-102.9801, -102.9801, -102.9801,  ...,  -99.9801, -102.9801,
            -102.9801],
           [-102.9801, -102.9801, -102.9801,  ...,  -99.9801, -102.9801,
            -102.9801],
           [-102.9801, -102.9801, -102.9801,  ...,  -99.9801, -102.9801,
            -102.9801],
           ...,
           [-102.9801, -102.9801, -102.9801,  ...,  -99.9801, -102.9801,
            -102.9801],
           [-102.9801, -102.9801, -102.9801,  ...,  -99.9801, -102.9801,
            -102.9801],
           [-102.9801, -102.9801, -102.9801,  ...,  -99.9801, -102.9801,
            -102.9801]],
 
          [[-115.9465, -115.9465, -115.9465,  ..., -112.9465, -115.9465,
            -115.9465],
           [-115.9465, -115.9465, -115.9465,  ..., -112.9465, -115.9465,
            -115.9465],
           [-115.9465, -115.9465, -115.9465,  ..., -112.9465, -115.9465,
            -115.9465],
           ...,
           [-115.9465, -115.9465, -115.9465,  ..., -112.9465, -115.9465,
            -115.94

In [13]:
imgs = test_images
batch_sz=64
n_batch = len(imgs)//batch_sz
res_batch = len(imgs)%batch_sz    

In [14]:
    with torch.no_grad():
        for i in range(n_batch):
            in_batch = torch.cat(imgs[i*batch_sz:(i+1)*batch_sz]).to('cuda')
#             x = rcnn_intermediate(frcnn_model, in_batch)
#             in_batch.to('cpu')
#             outputs.append(x)

#         # last incomplete batch.
#         in_batch = torch.cat(imgs[-res_batch:]).to('cuda')

In [15]:
in_batch[0].size()


torch.Size([3, 640, 480])

## get feature map

In [25]:
get_features(new_frcnn_model,test_images, batch_sz=64)

TypeError: 'str' object is not callable

In [30]:
new_frcnn_model

OrderedDict([('backbone.vgg_block1.0.conv1.weight',
              tensor([[[[ 4.2947e-01,  3.7347e-01, -6.1360e-02],
                        [ 2.7477e-01,  3.8681e-02, -3.6722e-01],
                        [-5.7468e-02, -2.6225e-01, -3.5010e-01]],
              
                       [[ 5.5038e-01,  4.4007e-01, -8.1387e-02],
                        [ 3.4574e-01,  4.0632e-02, -4.5350e-01],
                        [-5.8635e-02, -3.3067e-01, -4.8503e-01]],
              
                       [[ 4.8002e-01,  4.0855e-01, -6.5146e-02],
                        [ 3.1048e-01,  5.0202e-02, -4.0338e-01],
                        [-5.0872e-02, -2.8523e-01, -4.1852e-01]]],
              
              
                      [[[ 1.1727e-01,  1.6206e-01,  1.3569e-01],
                        [ 1.4835e-01,  2.0230e-01,  1.6169e-01],
                        [ 1.2934e-01,  1.7157e-01,  1.3871e-01]],
              
                       [[ 2.0877e-02,  4.7341e-02,  4.1854e-02],
                       

In [33]:
for idx,(key,value) in enumerate(new_frcnn_model.items()):
    print(value)

tensor([[[[ 4.2947e-01,  3.7347e-01, -6.1360e-02],
          [ 2.7477e-01,  3.8681e-02, -3.6722e-01],
          [-5.7468e-02, -2.6225e-01, -3.5010e-01]],

         [[ 5.5038e-01,  4.4007e-01, -8.1387e-02],
          [ 3.4574e-01,  4.0632e-02, -4.5350e-01],
          [-5.8635e-02, -3.3067e-01, -4.8503e-01]],

         [[ 4.8002e-01,  4.0855e-01, -6.5146e-02],
          [ 3.1048e-01,  5.0202e-02, -4.0338e-01],
          [-5.0872e-02, -2.8523e-01, -4.1852e-01]]],


        [[[ 1.1727e-01,  1.6206e-01,  1.3569e-01],
          [ 1.4835e-01,  2.0230e-01,  1.6169e-01],
          [ 1.2934e-01,  1.7157e-01,  1.3871e-01]],

         [[ 2.0877e-02,  4.7341e-02,  4.1854e-02],
          [ 3.1049e-02,  6.5810e-02,  4.6257e-02],
          [ 3.1679e-02,  5.4710e-02,  4.2320e-02]],

         [[-1.7270e-01, -1.7038e-01, -1.5435e-01],
          [-1.8760e-01, -1.7757e-01, -1.7440e-01],
          [-1.6600e-01, -1.6667e-01, -1.5705e-01]]],


        [[[ 3.4013e-02,  1.7086e-03, -1.1569e-01],
          [ 1.6

tensor([ 7.3516e-03, -3.1511e-02, -1.0037e+00, -6.1935e-01, -5.0354e-01,
        -7.0113e-01, -3.8090e-01, -3.4030e-01,  9.1096e-03, -6.4039e-03,
        -2.9102e-01, -4.5177e-01, -2.6054e-01, -3.3522e-01, -2.3289e-01,
        -2.5481e-01, -1.6774e-02,  5.8900e-03, -4.3445e-01, -1.2536e+00,
        -3.2857e-01, -5.4723e-01, -2.7575e-01, -3.1360e-01, -8.7447e-04,
        -1.6165e-02, -7.8954e-02, -2.5209e-02, -1.0328e-01, -1.0559e-01,
        -9.5523e-02, -9.2335e-02,  1.1649e-03, -1.7628e-02, -4.9729e-02,
        -1.0292e-01, -1.2216e-01, -1.2056e-01, -1.1820e-01, -1.1169e-01,
         3.2106e-03,  7.5278e-04, -1.7140e-02, -7.9124e-02, -8.5609e-02,
        -8.8660e-02, -7.8339e-02, -7.7244e-02,  6.0224e-04,  6.5627e-05,
        -6.9266e-03, -6.3347e-03, -2.6157e-02, -2.6212e-02, -2.4266e-02,
        -2.3471e-02, -3.2770e-03, -3.5071e-03, -2.9742e-02, -1.7793e-02,
        -4.5360e-02, -4.6456e-02, -4.2036e-02, -3.9474e-02,  9.9427e-04,
         1.6816e-03, -1.5612e-02, -1.3274e-02, -3.8

In [34]:
new_frcnn_model.backbone

AttributeError: 'collections.OrderedDict' object has no attribute 'backbone'

In [27]:
for l in list(new_frcnn_model)[0]:
    print(l)
    x = l(in_batch)

b


TypeError: 'str' object is not callable

In [ ]:
 features = self.backbone(images.tensor)

## dataloader

In [35]:
from Nb_utils import *
cfg_path = "configs/multi-teacher/skf2c_foggy_sourceonly_FedMAbackbone.yaml"

cfg = setup_all(cfg_path)
model_path_list = cfg.MODEL.TEACHER_PATH  
teacher_trainer = cfg.MODEL.TEACHER_TRAINER

In [36]:
cfg.MODEL.TEACHER_PATH  

['output/FedMA_skf2c_source-only/FedMA_VOC2007_sim1_12.pth',
 'output/FedMA_skf2c_source-only/FedMA_VOC2007_kitti1_12.pth',
 'output/FedMA_skf2c_source-only/FedMA_VOC2007_foggytrain1_12.pth']

In [37]:
teacher_trainer

'sourceonly'

In [38]:
cfg

CfgNode({'VERSION': 2, 'MODEL': CfgNode({'LOAD_PROPOSALS': False, 'MASK_ON': False, 'KEYPOINT_ON': False, 'DEVICE': 'cuda', 'META_ARCHITECTURE': 'GuassianGeneralizedRCNN', 'WEIGHTS': '', 'PIXEL_MEAN': [103.53, 116.28, 123.675], 'PIXEL_STD': [1.0, 1.0, 1.0], 'BACKBONE': CfgNode({'NAME': 'build_vgg_backbone_dynamic', 'FREEZE_AT': 5}), 'FPN': CfgNode({'IN_FEATURES': [], 'OUT_CHANNELS': 256, 'NORM': '', 'FUSE_TYPE': 'sum'}), 'PROPOSAL_GENERATOR': CfgNode({'NAME': 'GuassianRPN', 'MIN_SIZE': 0}), 'ANCHOR_GENERATOR': CfgNode({'NAME': 'DefaultAnchorGenerator', 'SIZES': [[128, 256, 512]], 'ASPECT_RATIOS': [[0.5, 1.0, 2.0]], 'ANGLES': [[-90, 0, 90]], 'OFFSET': 0.0, 'ANCHOR': [[[181.0193, 90.5097], [128.0, 128.0], [90.5097, 181.0193], [362.0387, 181.0193], [256.0, 256.0], [181.0193, 362.0387], [724.0773, 362.0387], [512.0, 512.0], [362.0387, 724.0773]]]}), 'RPN': CfgNode({'HEAD_NAME': 'GuassianRPNHead', 'IN_FEATURES': ['vgg_block5'], 'BOUNDARY_THRESH': -1, 'IOU_THRESHOLDS': [0.3, 0.7], 'IOU_LABEL

In [45]:
from detectron2.data import (
    DatasetCatalog,
    MetadataCatalog,
    build_detection_train_loader,
)

In [48]:
from pt.engine.trainer_sourceonly import PTrainer_sourceonly
Trainer = PTrainer_sourceonly

In [46]:
data_loader = build_detectron_train_loader(cfg)



NameError: name 'build_detectron_train_loader' is not defined

In [ ]:
model = self.build_model(cfg, cfg.BACKBONE_DIM, False)

In [ ]:
data = next(self._trainer._data_loader_iter)
# data_q and data_k from different augmentations (q:strong, k:weak)
# label_strong, label_weak, unlabed_strong, unlabled_weak
label_data_q, label_data_k = data
data_time = time.perf_counter() - start

# source only stage (supervised training with labeled data)

# -------------------------------
# input both strong and weak supervised data into model
label_data_q.extend(label_data_k)

label_data_q = self.resize(label_data_q)


_, feature_map, _, _ = self.model(label_data_q, branch="unsup_get_features_only")

In [8]:

data = next(Trainer._trainer._data_loader_iter)

AttributeError: type object 'FLtrainer' has no attribute '_trainer'

In [5]:
from Nb_utils import *
from detectron2.data.build import build_batch_data_loader


FLTrainer data_loader = self.build_train_loader(cfg)
def build_train_loader(cls, cfg):
        mapper = DatasetMapperTwoCropSeparate(cfg, True)
        return build_detection_targetonly_loader_two_crops(cfg, mapper)
    
    
cfg_path = "configs/multi-teacher/skf2c_foggy_sourceonly_FedMAbackbone.yaml"
cfg = setup_all(cfg_path)
data_loader = build_detection_train_loader(cfg)


NameError: name 'build_detection_train_loader' is not defined